# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p2p.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tp2p.proto\"\x1d\n\rUploadRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"!\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x11\n\x0f\x44ownloadRequest\" \n\x10\x44ownloadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2h\n\nP2PService\x12)\n\x06Upload\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\x12/\n\x08\x44ownload\x12\x10.DownloadRequest\x1a\x11.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOADREQUEST']._serialized_start=13
  _globals['_UPLOADREQUEST']._serialized_end=42
  _globals['_UPLOADRESPONSE']._serialized_start=44
  _globals['_UPLOADRESPONSE']._serialized_end=77
  _globals['_DOWNLOADREQUEST']._serialized_start=79
  _globals['_DOWNLOADREQUEST']._serialized_end=96
  _globals['_DOWNLOADRESPONSE']._serialized_start=98
  _globals['_DOWNLOADRESPONSE']._serialized_end=130
  _globals['_P2PSERVICE']._serialized_start=132
  _globals['_P2PSERVICE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
